services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: iuh_dynamodb_local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: iuh_dynamodb_admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

  localstack:
    image: localstack/localstack
    container_name: iuh_localstack_s3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1